name: benchmark_of_json_parsers_in_dart
description: Benchmark of json parsers in Dart.
version: 0.0.1
homepage: https://github.com/minikin/benchmark_of_json_parsers_in_dart

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
 benchmark_harness: ^2.0.0-nullsafety.0 # https://flutter.dev/docs/testing/code-debugging#tracing-dart-code-performance
 built_collection: ^5.0.0-nullsafety.0
 built_value: ^8.0.0-nullsafety.0
 json_serializable: ^3.5.0
 jsontool: ^1.0.1
 path: ^1.8.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
