name: benchmark_of_json_parsers_in_dart
description: A sample command-line application.
version: 0.0.1
homepage: https://github.com/minikin/benchmark_of_json_parsers_in_dart

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
 built_collection: ^4.3.2
 built_value: ^7.1.0
 json_serializable: ^3.5.0
 jsontool: ^1.0.1
 path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.4
  pedantic: ^1.9.0
  test: ^1.14.4
